### ISSUE TITLE
All the settings except vibrate are resetting immediately.

### ISSUE THREAD

**Issue by Swagmiral** [anselm94/Torchie-Android#25] opened 2019-05-30 22:24 UTC
I can't change any of the in-app settings except "Vibrate". For example: I turn off "Proximity sense", then I close the settings menu, and when I open it again - it's set to ON again, this happens to all the other settings as well (except Vibrate). 

Also, for some reason it added another volume slider (with Chromecast icon)  and uses it for default when when using volume keys and the phone is locked, so basically now I can't change the volume when my phone is locked because it uses this Cast volume slider instead of the main (real) one.

Phone: OnePlus  5t
OxygenOS 9.0.5

![Screenshot_20190531-012331](https://user-images.githubusercontent.com/14266587/58668809-c7856880-8342-11e9-9823-7211b6cddf46.jpg)

**Comment by anselm94** [comment] 2019-06-01 03:56
Do you face this issue in Beta version 3.2?

**Comment by Swagmiral** [comment] 2019-06-01 08:53
Yes

**Comment by anselm94** [comment] 2019-06-01 16:34
@Swagmiral The settings not getting persisited is fixed now. 

Regarding the other issue, the "Cast" volume control appears briefly, before disappearing completely. This is due to the latency in Android system in informing the application about "Screen On".

Have marked this for enhancement. Closing this issue for now.

**Comment by Swagmiral** [comment] 2019-06-01 16:39
The cast slider doesn't disappear until I unlock the phone.

**Comment by anselm94** [comment] 2019-06-02 04:34
@Swagmiral Yes. I'm able reproduce the issue in my OP5T. While in Screen Off, Torchie takes hold of Cast stream (as Music stream doesn't provide volume changes callback) for volume changes. On Screen on, it takes a brief time to release the stream.

Reopening the issue now

**Comment by anselm94** [comment] 2019-06-08 05:45
@Swagmiral This issue is fixed (9e584003ef834f20b3e085f2140bb936492771bb) in the latest 3.2.1 release available in Google Play Store

**Closed as completed by anselm94** 2019-06-08 05:45 UTC
Labels: bug, enhancement
