### ISSUE TITLE
Turns on if on button and volume button pressed together

### ISSUE THREAD

**Issue by snelltheta** [anselm94/Torchie-Android#5] opened 2016-02-20 01:44 UTC
This wouldn't be much of an issue if 

It didn't happen 
Or, if there was a setting to make it so that only volume buttons turn it on or off.

**Comment by anselm94** [comment] 2016-02-22 17:39
May be that Power button wakes the system first and turns the flash on, since both the volume buttons are held

**Comment by snelltheta** [comment] 2016-02-23 16:16
But both volume buttons are not held and it turns on.

**Comment by zamber** [comment] 2016-02-25 14:00
Can't reproduce on OnePlus Two with stock 5.1.1. @snelltheta, what device are you using? Also, please provide clear reproduction steps (including settings you changed, if any). having a logcat would be stellar too.

**Comment by smichel17** [comment] 2017-06-03 22:19
I also can't reproduce, on Galaxy S6 (SM-G920A) with 7.0.

**Comment by anselm94** [comment] 2019-05-30 17:22
Closing the issue, as the reporter has not come back in a long time. Moreover it's not reproducible in other phones.
@snelltheta Please feel free to re-open this issue, if the problem persists.

**Closed as completed by anselm94** 2019-05-30 17:22 UTC
